stages:
  - build
  - image
  - update-manifest

variables:
  IMAGE_NAME: harbor.internal/library/cicd-app
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_CONFIG: /kaniko/.docker

#################################
# 1️⃣ Build JAR
#################################
build-jar:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - cd app
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - app/target/demo-0.0.1.jar
    expire_in: 1 hour
  only:
    - dev
    - main

#################################
# 2️⃣ Build & Push Image
#################################
build-image:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:debug
  dependencies:
    - build-jar
  script:
    - mkdir -p "$DOCKER_CONFIG"
    - |
      cat > "$DOCKER_CONFIG/config.json" <<EOF
      {
        "auths": {
          "harbor.internal": {
            "username": "$HARBOR_USER",
            "password": "$HARBOR_PASSWORD"
          }
        }
      }
      EOF

    - |
      /kaniko/executor \
        --context "$CI_PROJECT_DIR/app" \
        --dockerfile "$CI_PROJECT_DIR/app/Dockerfile" \
        --destination "$IMAGE_NAME:$IMAGE_TAG" \
        --insecure \
        --insecure-pull \
        --skip-push-permission-check \
        --no-cache
  only:
    - dev
    - main

#################################
# 3️⃣ Update kustomize image tag (핵심)
#################################
update-manifest-dev:
  stage: update-manifest
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.email "ci@gitlab"
    - git config --global user.name "gitlab-ci"
    - sed -i 's|newTag:.*|newTag: '"$IMAGE_TAG"'|g' kustomize/overlays/dev/kustomization.yaml
    - git add kustomize/overlays/dev/kustomization.yaml
    - git commit -m "Update image tag to $IMAGE_TAG"
    - "git push https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.internal/root/pjt-cicd.git HEAD:dev"
  only:
    - dev
