stages:
  - build
  - image
  - deploy

variables:
  IMAGE_NAME: harbor.internal/library/cicd-app
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_CONFIG: /kaniko/.docker

#################################
# 1️⃣ Build JAR
#################################
build-jar:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - cd app
    - mvn clean package -DskipTests
    - ls -l target
  artifacts:
    paths:
      - app/target/demo-0.0.1.jar
    expire_in: 1 hour
  only:
    - dev
    - main

#################################
# 2️⃣ Build & Push Image
#################################
build-image:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:debug
  dependencies:
    - build-jar
  script:
    - echo "===== JAR 확인 ====="
    - ls -l app/target

    - mkdir -p "$DOCKER_CONFIG"
    - |
      cat > "$DOCKER_CONFIG/config.json" <<EOF
      {
        "auths": {
          "harbor.internal": {
            "username": "$HARBOR_USER",
            "password": "$HARBOR_PASSWORD"
          }
        }
      }
      EOF

    - |
      /kaniko/executor \
        --context "$CI_PROJECT_DIR/app" \
        --dockerfile "$CI_PROJECT_DIR/app/Dockerfile" \
        --destination "$IMAGE_NAME:$IMAGE_TAG" \
        --insecure \
        --insecure-pull \
        --skip-push-permission-check \
        --no-cache
  only:
    - dev
    - main

#################################
# 3️⃣ Deploy (kubectl 유지 버전)
#################################
deploy-dev:
  stage: deploy
  image: bitnami/kubectl:latest
  needs:
    - build-image
  script:
    - kubectl set image deployment/cicd-app cicd-app=$IMAGE_NAME:$IMAGE_TAG -n dev
    - kubectl rollout status deployment/cicd-app -n dev
  only:
    - dev

deploy-prd:
  stage: deploy
  image: bitnami/kubectl:latest
  needs:
    - build-image
  script:
    - kubectl set image deployment/cicd-app cicd-app=$IMAGE_NAME:$IMAGE_TAG -n prd
    - kubectl rollout status deployment/cicd-app -n prd
  only:
    - main

