stages:
  - build
  - image
  - deploy

variables:
  IMAGE_NAME: harbor.internal/library/cicd-app
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_CONFIG: /kaniko/.docker

############################
# 1️⃣ Java Build
############################
build-jar:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - cd app
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - app/target/*.jar
    expire_in: 1 hour
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"'

############################
# 2️⃣ Docker Image Build & Push (Kaniko)
############################
build-image:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:debug
  dependencies:
    - build-jar
  script:
    - mkdir -p "$DOCKER_CONFIG"
    - |
      cat > "$DOCKER_CONFIG/config.json" <<EOF
      {
        "auths": {
          "harbor.internal": {
            "username": "$HARBOR_USER",
            "password": "$HARBOR_PASSWORD"
          }
        }
      }
      EOF

    - |
      /kaniko/executor \
        --context "$CI_PROJECT_DIR/app" \
        --dockerfile "$CI_PROJECT_DIR/app/Dockerfile" \
        --destination "$IMAGE_NAME:$IMAGE_TAG" \
        --insecure \
        --insecure-pull \
        --skip-push-permission-check
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"'

############################
# 3️⃣ DEV Deploy
############################
deploy-dev:
  stage: deploy
  image: bitnami/kubectl:latest
  needs:
    - build-image
  script:
    - kubectl config use-context "$KUBE_CONTEXT_DEV"
    - kubectl set image deployment/cicd-app cicd-app=$IMAGE_NAME:$IMAGE_TAG -n dev
    - kubectl rollout status deployment/cicd-app -n dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'

############################
# 4️⃣ PRD Deploy
############################
deploy-prd:
  stage: deploy
  image: bitnami/kubectl:latest
  needs:
    - build-image
  script:
    - kubectl config use-context "$KUBE_CONTEXT_PRD"
    - kubectl set image deployment/cicd-app cicd-app=$IMAGE_NAME:$IMAGE_TAG -n prd
    - kubectl rollout status deployment/cicd-app -n prd
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

