stages:
  - build
  - image
  - deploy

variables:
  IMAGE_NAME: harbor.internal/library/cicd-app
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_CONFIG: /kaniko/.docker

# 1. Java 빌드 단계
build-jar:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - cd app
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - app/target/*.jar
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - app/**/*
        - pom.xml

# 2. 이미지 빌드 & 푸시 단계
build-image:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:debug
  dependencies:
    - build-jar
  script:
    # Harbor 인증
    - mkdir -p "$DOCKER_CONFIG"
    - |
      cat > "$DOCKER_CONFIG/config.json" <<EOF
      {
        "auths": {
          "harbor.internal": {
            "username": "$HARBOR_USER",
            "password": "$HARBOR_PASSWORD"
          }
        }
      }
      EOF

    # Kaniko build & push
    - |
      /kaniko/executor \
        --context "$CI_PROJECT_DIR/app" \
        --dockerfile "$CI_PROJECT_DIR/app/Dockerfile" \
        --destination "$IMAGE_NAME:$IMAGE_TAG" \
        --insecure \
        --insecure-pull \
        --skip-push-permission-check
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

update-kustomize-dev:
  stage: deploy
  image: alpine/git:latest
  needs:
    - build-image
  before_script:
    - git config --global user.email "ci@gitlab.internal"
    - git config --global user.name "gitlab-ci"
  script:
    - 'sed -i "s/newTag:.*/newTag: ${IMAGE_TAG}/" kustomize/overlays/dev/kustomization.yaml'
    - 'git add kustomize/overlays/dev/kustomization.yaml'
    - 'git commit -m "deploy(dev): ${IMAGE_TAG}" || echo "no change"'
    - 'git push https://root:${GITLAB_TOKEN}@gitlab.internal/root/pjt-cicd.git HEAD:main'
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      
