stages:
  - build

variables:
  IMAGE_NAME: harbor.internal/library/cicd-app
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_CONFIG: /kaniko/.docker

build-image:
  stage: build
  image: gcr.io/kaniko-project/executor:v1.23.2
  script:
    # Harbor auth
    - mkdir -p "$DOCKER_CONFIG"
    - |
      cat > "$DOCKER_CONFIG/config.json" <<EOF
      {
        "auths": {
          "harbor.internal": {
            "username": "$HARBOR_USER",
            "password": "$HARBOR_PASSWORD"
          }
        }
      }
      EOF

    # Kaniko build
    - |
      /kaniko/executor \
        --context "$CI_PROJECT_DIR/app" \
        --dockerfile Dockerfile \
        --destination "$IMAGE_NAME:$IMAGE_TAG" \
        --skip-tls-verify \
        --skip-tls-verify-pull \
        --cache=true

  rules:
    - if: $CI_COMMIT_BRANCH == "main"

