stages:
  - build

variables:
  IMAGE_NAME: harbor.internal/library/cicd-app
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_CONFIG: /kaniko/.docker

build-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
  script:
    # Harbor 인증
    - mkdir -p "$DOCKER_CONFIG"
    - |
      cat > "$DOCKER_CONFIG/config.json" <<EOF
      {
        "auths": {
          "harbor.internal": {
            "username": "$HARBOR_USER",
            "password": "$HARBOR_PASSWORD"
          }
        }
      }
      EOF

    # Kaniko build & push
    - |
      /kaniko/executor \
        --context "$CI_PROJECT_DIR/app" \
        --dockerfile "$CI_PROJECT_DIR/app/Dockerfile" \
        --destination "$IMAGE_NAME:$IMAGE_TAG" \
        --insecure \
        --insecure-pull \
        --skip-push-permission-check
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - app/**/*
        - Dockerfile
        - .gitlab-ci.yml
