apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: dev.djlee.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cicd-app
            port:
              number: 80

